---
# tasks file for skywire-manager

- template:
    src: skywire-node.service.j2
    dest: /etc/systemd/system/skywire-node.service
  register: newunit

- stat:
    path: /etc/default/skywire-node
  register: stat_result

- file:
    path: /etc/default/skywire-node
    state: touch
  when: stat_result.stat.exists == False 

- systemd:
    daemon_reload: yes

- systemd:
    name: skywire-node
    enabled: True
    state: started    
  when: newunit.changed
  
